# A sample Gemfile
source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-jsonp'
gem 'sinatra-contrib',        require: false
gem 'nokogiri'
gem 'oj'
gem 'hiredis'
gem 'redis', require: %w[redis/connection/hiredis redis]
gem 'rest-client'

gem 'pry',                    require: false
gem 'binding_of_caller',      require: false
gem 'pry-stack_explorer',     require: false
gem 'awesome_print',          require: false
gem 'pry-remote',             require: false
gem 'pry-remote-auto',        require: false, git: 'git@github.com:Pavliko/pry-remote-auto.git'

gem 'shotgun',                require: false
gem 'unicorn',                require: false
