# A sample Gemfile
source 'https://rubygems.org'


gem 'sinatra'
gem 'sinatra-jsonp'
gem 'sinatra-contrib'
gem 'shotgun',      :require => false
gem 'unicorn',      :require => false
gem 'mina',         :require => false
gem 'mina-unicorn', :require => false
gem 'nokogiri',     :require => false
gem 'rest-client',  :require => false
